### ISSUE TITLE
Support for ScanTweaks mod

### ISSUE THREAD

**Issue by cangming99** [Test-Account666/LethalCompany-ScanShipEverywhere#1]
When I use ScanTweaks, if the distance is too far, it still cannot be scanned. However, when I turn off ScanTweaks, it works again. I hope the support for ScanTweaks can be strengthened once more.Thank you.

**Comment by Test-Account666** [comment]
Hello!

Thanks for the report :)

I'm currently looking into this, but I'm unsure what's limiting ScanTweak's range here...

**Comment by Test-Account666** [comment]
Issue should be resolved.

Scanning far away nodes takes a while though
