### ISSUE TITLE
Known incompatibility with General Improvements

### ISSUE THREAD

**Issue by NeatWolf** [Test-Account666/LethalCompany-ScanShipEverywhere#2]
Hi - I noticed the log mentions SSE is not compatible with GI's FixPersonalScanner toggle - An Info message from GI.

> [Scanner]
> ## If set to true, will tweak the behavior of the scan action and more reliably ping items closer to you, and the ship/main entrance.
> FixPersonalScanner = true

Is there any chance you could please look into that incompatibility? I honestly was unaware this was even an issue - I found it by pure chance.
Sadly disabling that toggle it definitely makes the scanner way less accurate.

**Comment by Test-Account666** [comment]
Hello!

I added this message as a placeholder until I can find a way to support it.

So, it is being worked on :)

**Comment by Test-Account666** [comment]
Incompatibility resolved :)

I still recommend other mods (Like my GoodItemScan) though
